
 storages:
   - name: main
     plugin: fs
     config:
       directory: /var/lib/yandex/unified_agent/main
       max_partition_size: 100mb
       max_segment_size: 10mb

 channels:
   - name: cloud_monitoring
     channel:
       pipe:
         - storage_ref:
             name: main
       output:
         plugin: yc_metrics
         config:
           folder_id: "b1g8vp06auhfbk8j09np"
           iam:
             cloud_meta: {}

 routes:
   - input:
       plugin: metrics_pull
       config:
         url: http://django-app-with-gunicorn:8888
         format:
           prometheus: {}
         namespace: app
     channel:
       channel_ref:
         name: cloud_monitoring