stages:
  - tests
  - build


check_lint:
  stage: tests
  tags:
    - code

  image: python:3.10.10-slim-buster

  before_script:
    - apt-get update && apt-get install make
    - pip3 install flake8 black isort 

  script:
    - make check_lint

  needs: []

test:
  stage: tests
  tags:
    - code

  image: python:3.10.10-slim-buster 
  before_script:
   - apt-get update && apt-get install make
   - pip3 install pipenv

   - pipenv install --dev --system

  script:
    - pipenv run pytest

  needs: []


build:
  stage: build
  image: docker:23.0.1
  tags:
    - code

  services:
    - name: docker:23.0.1-dind

  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""

    TAG_LATEST: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest
    TAG_COMMIT: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA

    
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY 

  script:
    - docker pull $TAG_LATEST || true 
    - DOCKER_BUILDKIT=1 docker build --cache-from $TAG_LATEST --build-arg BUILDKIT_INLINE_CACHE=1 -t $TAG_COMMIT -t $TAG_LATEST -f Dockerfile.server .

    - docker push $TAG_COMMIT
    - docker push $TAG_LATEST

